### ISSUE TITLE
Mouse Coords 

### ISSUE THREAD

**Issue by Kobrairaq** [maptiler/get-started-react-maplibre-gl-js#1]
How to get Mouse Coords using React hooks ?

**Comment by bolollo** [comment]
Hi, to get the mouse coordinates you can use the MouseMove callback (https://visgl.github.io/react-map-gl/docs/api-reference/map#onmousemove) or any other callback that has an event of the mouse. mouse.

It would be something like this:

```
function App() {

  const onMouseMove = useCallback((event) => console.log(event.lngLat), []);

  return (
    <div className="App">
      <Navbar/>
      <Map mapLib={maplibregl} 
        initialViewState={{
          longitude: 16.62662018,
          latitude: 49.2125578,
          zoom: 14
        }}
        style={{width: "100%", height: " calc(100vh - 77px)"}}
        mapStyle="https://api.maptiler.com/maps/streets/style.json?key=c6RyyxE2c8qRPnEgF4VV"
        onMouseMove={onMouseMove}
      >
        <NavigationControl position="top-left" />
      </Map>
    </div>
  );
}
```

Here you can see another example of how it is used with hooks https://github.com/visgl/react-map-gl/blob/7.0-release/examples/custom-cursor/src/app.tsx

**Comment by Kobrairaq** [comment]
thank you very much @bolollo
